from django.contrib import admin
from .models import *

admin.site.register(CharacterType)
admin.site.register(VirtueType)
admin.site.register(House)
admin.site.register(Virtue)
admin.site.register(Character)
admin.site.register(CharacterVirtue)
admin.site.register(Characteristic)
admin.site.register(CharacterCharacteristic)
admin.site.register(AbilityType)
admin.site.register(Ability)
admin.site.register(CharacterAbility)
admin.site.register(XPSource)
admin.site.register(CharacterAbilityXP)
admin.site.register(Art)
admin.site.register(CharacterArt)
admin.site.register(CharacterArtXP)
admin.site.register(Spell)
admin.site.register(CharacterSpell)
